// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameTbConcert = "tb_concert"

// TbConcert mapped from table <tb_concert>
type TbConcert struct {
	ID            int64  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	ConcertID     string `gorm:"column:concert_id;not null" json:"concertId"`
	ConcertName   string `gorm:"column:concert_name;not null" json:"concertName"`
	ConcertImgURL string `gorm:"column:concert_img_url;not null" json:"concertImgUrl"`
	ConcertDate   int64  `gorm:"column:concert_date;not null" json:"concertDate"`
	ConcertStatus int  `gorm:"column:concert_status;not null" json:"concertStatus"`
	Status        int `gorm:"column:status;not null" json:"status"`
	CreateAt      int64  `gorm:"column:create_at;not null" json:"createAt"`
	UpdateAt      int64  `gorm:"column:update_at;not null" json:"updateAt"`
}

// TableName TbConcert's table name
func (*TbConcert) TableName() string {
	return TableNameTbConcert
}
