// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameTbTicket = "tb_ticket"

// TbTicket mapped from table <tb_ticket>
type TbTicket struct {
	ID                   int64   `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	ConcertID            string  `gorm:"column:concert_id;not null" json:"concertId"`
	TicketType           int64   `gorm:"column:ticket_type;not null" json:"ticketType"`
	TypeName             string  `gorm:"column:type_name;not null" json:"typeName"`
	Price                float64 `gorm:"column:price;not null" json:"price"`
	MaxQuantityPerWallet int64   `gorm:"column:max_quantity_per_wallet;not null" json:"maxQuantityPerWallet"`
	CreateAt             int64   `gorm:"column:create_at;not null" json:"createAt"`
	UpdateAt             int64   `gorm:"column:update_at;not null" json:"updateAt"`
}

// TableName TbTicket's table name
func (*TbTicket) TableName() string {
	return TableNameTbTicket
}
