// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameTbUser = "tb_user"

// TbUser mapped from table <tb_user>
type TbUser struct {
	ID                       int64  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Email                    string `gorm:"column:email;not null" json:"email"`
	Phone                    string `gorm:"column:phone;not null" json:"phone"`
	IdentityDocumentType     int64  `gorm:"column:identity_document_type;not null" json:"identityDocumentType"`
	IdentityDocumentNumber   string `gorm:"column:identity_document_number;not null" json:"identityDocumentNumber"`
	IdentityDocumentCountry  string `gorm:"column:identity_document_country;not null" json:"identityDocumentCountry"`
	IdentityDocumentImageURL string `gorm:"column:identity_document_image_url;not null" json:"identityDocumentImageUrl"`
	WalletAddress            string `gorm:"column:wallet_address;not null" json:"walletAddress"`
	Password                 string `gorm:"column:password;not null" json:"password"`
	CreateAt                 int64  `gorm:"column:create_at;not null" json:"createAt"`
	UpdateAt                 int64  `gorm:"column:update_at;not null" json:"updateAt"`
}

// TableName TbUser's table name
func (*TbUser) TableName() string {
	return TableNameTbUser
}
