server:
  name: ""
  port: ":8080"
  mode: "dev"

zap:
  level: info
  format: console
  prefix: "[ChainDraw]"
  director: logs
  show-line: true
  encode-level: LowercaseColorLevelEncoder
  stacktrace-key: stacktrace
  log-in-console: true

mysql:
  host: "127.0.0.1"
  port: 3306
  dbname: "chaindraw_fair_ticket"
  user: "root"
  password: "root"
  max_open_conns: 200
  max_idle_conns: 50

redis:
  host: "127.0.0.1"
  port: 6379